const URL_PATHS = {
  GET_CAMPAIGN: "GET_CAMPAIGN",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  GET_BUSINESS: "/business/get-list",
  GET_DETAIL_BUSINESS: "/business/get/:id",
  CREATE_BUSINESS: "/business/create",
  UPDATE_BUSINESS: "/business/update/:id",
  DELETE_BUSINESS: "/business/delete/:id",
  GET_CAMPAIGNS: "/campaigns/get-list",
  GET_DETAIL_CAMPAIGNS: "/campaigns/get/:id",
  CREATE_CAMPAIGNS: "/campaigns/create",
  UPDATE_CAMPAIGNS: "/campaigns/update/:id",
  DELETE_CAMPAIGNS: "/campaigns/delete/:id",
  GET_CAMPAIGS: '/campaigns/get-list',
  GET_DETAIL_CAMPAIGS: '/campaigns/get/:id',
  GET_AD_SET: '/ad_sets/get-list',
  GET_DETAIL_AD_SET: '/ad_sets/get/:id',
  CREATE_AD_SET: "/ad_sets/create",
  UPDATE_AD_SET: "/ad_sets/update/:id",
  DELETE_AD_SET: "/ad_sets/delete/:id",
  GET_AD: '/ads/get-list',
  GET_DETAIL_AD: '/ads/get/:id',
  CREATE_AD: "/ads/create",
  UPDATE_AD: "/ads/update/:id",
  DELETE_AD: "/ads/delete/:id",
  UPLOAD_IMAGE: "/upload/image",
  DELETE_IMAGE: "/upload/image/:filename",
  GET_DETAIL_IMAGE: "/form_face/get",
  UPDATE_IMAGE: "/form_face/update",
};

export default URL_PATHS;
