export const METRICS_MENU = [
  {
    key: "Popular metrics",
    listChild: [
      {
        label: "Amount spent",
        isShow: true,
      },
      {
        label: "Impressions",
        isShow: true,
      },
      {
        label: "Reach",
        isShow: true,
      },
      {
        label: "Frequency",
        isShow: true,
      },
      {
        label: "Purchases",
        isShow: false,
      },
      {
        label: "Cost per purchase",
        isShow: false,
      },
      {
        label: "Purchases conversion value",
        isShow: false,
      },
      {
        label: "Link clicks",
        isShow: false,
      },
      {
        label: "CPC (cost per link click)",
        isShow: false,
      },
      {
        label: "Clicks (all)",
        isShow: false,
      },
      {
        label: "CPC (all)",
        isShow: false,
      },
      {
        label: "CPM (cost per 1,000 impressions)",
        isShow: false,
      },
      {
        label: "CTR (all)",
        isShow: false,
      },
    ],
  },
  {
    key: "Custom metrics",
    listChild: [],
  },
  {
    key: "Performance",
    listChild: [
      {
        label: "Reach",
        isShow: true,
      },
      {
        label: "Frequency",
        isShow: true,
      },
      {
        label: "Impressions",
        isShow: true,
      },
      {
        label: "Views",
        isShow: false,
      },
      {
        label: "Amount spent",
        isShow: true,
      },
      {
        label: "Click (all)",
        isShow: false,
      },
      {
        label: "CPC (all)",
        isShow: false,
      },
      {
        label: "CTR (all)",
        isShow: false,
      },
      {
        label:
          "Gross impressions (includes invalid impressions from non-human traffic)",
        isShow: false,
      },
      {
        label: "Auto-refresh impressions",
        isShow: true,
      },
      {
        label: "Purchases rate per landing page views",
        isShow: false,
      },
      {
        label: "Cost per 1,000 Accounts Centre accounts reached",
        isShow: false,
      },
      {
        label: "CPM (cost per 1,000 impressions)",
        isShow: false,
      },
      {
        label: "Ad delivery",
        isShow: false,
      },
      {
        label: "Ad set delivery",
        isShow: false,
      },
      {
        label: "Campaign delivery",
        isShow: false,
      },
    ],
  },
  {
    key: "Engagement",
    listChild: [
      {
        label: "Page engagement",
        isShow: false,
      },
      {
        label: "Facebook follows or likes",
        isShow: false,
      },
      {
        label: "Post comments",
        isShow: false,
      },
      {
        label: "Post engagements",
        isShow: false,
      },
      {
        label: "Post reactions",
        isShow: false,
      },
      {
        label: "Post shares",
        isShow: false,
      },
      {
        label: "Photo views",
        isShow: false,
      },
      {
        label: "Check-ins",
        isShow: false,
      },
      { label: "Cost per Page engagement", isShow: false },
      { label: "Cost per follow or like", isShow: false },
      { label: "Cost per post engagement", isShow: false },
      { label: "Blocks", isShow: false },
      { label: "Messaging conversations started", isShow: false },
      { label: "Cost per messaging conversation started", isShow: false },
      { label: "3-second video plays", isShow: false },
      { label: "Video plays at 25%", isShow: false },
      { label: "Video plays at 50%", isShow: false },
      { label: "Video plays at 75%", isShow: false },
      { label: "Video plays at 95%", isShow: false },
      { label: "Video plays at 100%", isShow: false },
      { label: "Cost per 3-second video play", isShow: false },
      { label: "Link clicks", isShow: false },
      { label: "CTR (link click-through rate)", isShow: false },
      { label: "CPC (cost per link click)", isShow: false },
    ],
  },
  {
    key: "Conversions",
    listChild: [
      { label: "Achievements unlocked", isShow: false },
      { label: "Cost per achievement unlocked", isShow: false },
      { label: "Achievements unlocked conversion value", isShow: false },
      { label: "Adds of payment info", isShow: false },
      { label: "Cost per add of payment info", isShow: false },
      { label: "Adds of payment info conversion value", isShow: false },
      { label: "Adds to cart", isShow: false },
      { label: "Cost per add to cart", isShow: false },
      { label: "Adds to cart conversion value", isShow: false },
      { label: "Adds to wishlist", isShow: false },
      { label: "Cost per add to wishlist", isShow: false },
      { label: "Adds to wishlist conversion value", isShow: false },
      { label: "App activiations", isShow: false },
      { label: "Cost per app activation", isShow: false },
      { label: "App activations conversion value", isShow: false },
      { label: "App Installs", isShow: false },
      { label: "Cost per App Install", isShow: false },
      { label: "Applications submitted", isShow: false },
      { label: "Cost per application submitted", isShow: false },
      { label: "Submit Application conversion value", isShow: false },
      { label: "Appointments scheduled", isShow: false },
      { label: "Cost per appointment scheduled", isShow: false },
      { label: "Appointments scheduled conversion value", isShow: false },
      { label: "Checkouts initiated", isShow: false },
      { label: "Cost per checkout initiated", isShow: false },
      { label: "Checkouts initiated conversion value", isShow: false },
      { label: "Contacts", isShow: false },
      { label: "Cost per Contact", isShow: false },
      { label: "Contact conversion value", isShow: false },
      { label: "Content views", isShow: false },
      { label: "Cost per Content View", isShow: false },
      { label: "Content Views Conversion Value", isShow: false },
      { label: "Credit spends", isShow: false },
      { label: "Cost per credit spend", isShow: false },
      { label: "Credit spends conversion value", isShow: false },
      { label: "Custom events", isShow: false },
      { label: "Cost per custom event", isShow: false },
      { label: "Donations", isShow: false },
      { label: "Cost per donation", isShow: false },
      { label: "Donate conversion value", isShow: false },
      { label: "In-app ad clicks", isShow: false },
      { label: "Cost per in-app ad click", isShow: false },
    ],
  },
  {
    key: "Custom Conversions",
    listChild: null,
  },
  {
    key: "Settings",
    listChild: [
      { label: "Account ID", isShow: false },
      { label: "Account name", isShow: false },
      { label: "Reporting starts", isShow: false },
      { label: "Reporting ends", isShow: false },
      { label: "Objective", isShow: false },
      { label: "Buying type", isShow: false },
      { label: "Bid", isShow: false },
      { label: "Schedule", isShow: false },
      { label: "Ad ID", isShow: false },
      { label: "Ad name", isShow: false },
      { label: "Ad set budget", isShow: false },
      { label: "Ad set ID", isShow: false },
      { label: "Ad set name", isShow: false },
      { label: "Campaign budget", isShow: false },
      { label: "Campaign ID", isShow: false },
      { label: "Campaign name", isShow: false },
      { label: "Currency", isShow: false },
      { label: "Description", isShow: false },
      { label: "Headline (ad settings)", isShow: false },
      { label: "Website URL", isShow: false },
      { label: "Call to action", isShow: false },
      { label: "Image hash", isShow: false },
      { label: "Video ID", isShow: false },
      { label: "Image name", isShow: false },
      { label: "Video name", isShow: false },
      { label: "URL parameters", isShow: false },
      { label: "Included custom audiences", isShow: false },
      { label: "Excluded custom audiences", isShow: false },
    ],
  },
];
