import TooltipCustom from "@/components/TooltipCustom";
import { Box } from "@mui/material";
import React from "react";

const DeliveryRecommend = () => {
  return (
    <Box bgcolor="white" borderRadius="4px" marginTop="16px" padding="16px">
      <Box
        display="flex"
        justifyContent="space-between"
        alignItems="center"
        gap="8px"
      >
        <div>
          <p
            style={{ fontSize: "15px", fontWeight: "700", lineHeight: "20px" }}
          >
            Delivery recommendations
          </p>
          <p
            style={{ fontSize: "14px", fontWeight: "400", lineHeight: "20px" }}
          >
            Recommendations generated by current performance across your
            account.
          </p>
        </div>
        <TooltipCustom title="Share feedback" placement="top-start">
          <Box
            sx={{
              width: "16px",
              height: "16px",
              maskImage:
                "url(https://static.xx.fbcdn.net/rsrc.php/v4/yW/r/DG3IQ9pnrkn.png?_nc_eui2=AeHyg-hRTFM-2tHJ0xyJTbxZUrJBDbRMhIxSskENtEyEjPL0eTXyawvvyFfwvxzAn5x3wdMugaZqWt4ZK33tqnGw)",
              maskPosition: "-190px -386px",
              background: "#1c2b33",
            }}
          />
        </TooltipCustom>
      </Box>
    </Box>
  );
};

export default DeliveryRecommend;
